"""Direct smoke test: Google Workspace tools (create doc, send email, list calendar)."""
import os, sys, asyncio
from dotenv import load_dotenv

load_dotenv(os.path.join(os.path.dirname(__file__), ".env"))

from storage import SupabaseStore
from google_workspace import (
    create_google_doc,
    send_new_email,
    list_recent_emails,
    list_upcoming_events,
    ensure_valid_tokens,
    parse_email_address,
)

BASE = os.getenv("SUPABASE_URL")
KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")
USER_ID = "66b69c43-6d07-41cd-8058-f16a273bb7d6"

store = SupabaseStore(BASE, KEY)
errors = []

def test(name, fn):
    try:
        result = fn()
        print(f"  [OK] {name}")
        return result
    except Exception as e:
        print(f"  [FAIL] {name}: {e}")
        errors.append(f"{name}: {e}")
        return None

async def async_test(name, coro):
    try:
        result = await coro
        print(f"  [OK] {name}")
        return result
    except Exception as e:
        print(f"  [FAIL] {name}: {e}")
        errors.append(f"{name}: {e}")
        return None

async def main():
    print("\n=== SMOKE TEST: Google Workspace Features ===\n")

    # 1. Get fresh access token
    print("TOKEN REFRESH:")
    integration = store.get_google_integration(USER_ID)
    if not integration:
        print("  [FAIL] No Google integration found. Connect Google Workspace first.")
        sys.exit(1)
    
    print(f"  Google email: {integration.get('google_email')}")
    
    try:
        integration = await ensure_valid_tokens(integration)
        store.upsert_google_integration(USER_ID, integration)
        print("  [OK] Token refresh")
    except Exception as e:
        print(f"  [FAIL] Token refresh: {e}")
        sys.exit(1)
    
    access_token = integration["access_token"]

    # 2. Create Google Doc
    print("\nGOOGLE DOCS:")
    doc = await async_test(
        "create_google_doc",
        create_google_doc(
            access_token,
            "Saathi Smoke Test - Why Cancer is Hard to Cure",
            "Cancer is extremely difficult to cure because:\n\n"
            "1. Cancer cells are your own cells that have mutated\n"
            "2. Each tumor is genetically unique\n"
            "3. Cancer cells evolve and develop resistance to treatment\n"
            "4. Metastasis spreads cancer throughout the body\n"
            "5. The immune system often fails to recognize cancer cells\n\n"
            "This document was auto-generated by Saathi AI as a smoke test."
        )
    )
    if doc:
        print(f"    Doc URL: {doc.get('url')}")

    # 3. Send Email
    print("\nSEND EMAIL:")
    # Search for Khushi's email first
    emails = await async_test(
        "list_recent_emails (search for contacts)",
        list_recent_emails(access_token, max_results=20)
    )
    
    khushi_email = None
    if emails:
        for e in emails:
            sender = e.get("from", "").lower()
            if "khushi" in sender:
                khushi_email = parse_email_address(e["from"])
                print(f"    Found Khushi: {khushi_email}")
                break
    
    if khushi_email:
        result = await async_test(
            "send_email to Khushi",
            send_new_email(
                access_token,
                to=khushi_email,
                subject="You are beautiful (Saathi AI test)",
                body="Hey Khushi!\n\nJust wanted to tell you how beautiful you are. "
                     "This mail was sent by Saathi AI on behalf of Sharon to annoy you. :)\n\n"
                     "- Saathi AI"
            )
        )
    else:
        print("  [SKIP] Could not find Khushi's email in recent inbox. Sending test to self instead.")
        result = await async_test(
            "send_email to self (fallback)",
            send_new_email(
                access_token,
                to="sharonmelhi365@gmail.com",
                subject="Saathi Smoke Test - Email Works!",
                body="This email was sent by Saathi AI smoke test to verify the email feature works."
            )
        )

    # 4. Calendar
    print("\nCALENDAR:")
    events = await async_test(
        "list_upcoming_events",
        list_upcoming_events(access_token, timezone_name="Asia/Kolkata", max_results=5)
    )
    if events:
        print(f"    Found {len(events)} upcoming events")
        for ev in events[:3]:
            print(f"    - {ev.get('title')} ({ev.get('start')})")
    else:
        print("    No upcoming events")

    # Summary
    print(f"\n{'='*50}")
    if errors:
        print(f"FAILED: {len(errors)} test(s) failed:")
        for e in errors:
            print(f"  - {e}")
        sys.exit(1)
    else:
        print("ALL GOOGLE WORKSPACE TESTS PASSED")
        sys.exit(0)

asyncio.run(main())
